sudo: required
os: osx
env:
  global:
    - HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/lazzurs/homebrew-tfenv"

before_script:
  - brew update
script:
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - brew test-bot

